name: Deploy Docker Compose App

on:
  push:
    branches: [main] # Change this to your default branch if different
  # workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ostad-runner # This ensures the workflow runs on your machine

    steps:
      - name: Set up Docker Compose
        run: |
          docker-compose --version
      - name: Checking out code
        run: |
          # cd /home/ashik/selise/Projects/demoapp/
          cd /home/ubuntu/demoapp
          git stash
          git fetch
          git pull origin main
          # Build and start the containers
          docker-compose up -d --build

          # Remove unused images
          docker image prune -f
