name: Deploy Docker Compose App

on:
  push:
    branches: [main] # Change this to your default branch if different
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: self-hosted # This ensures the workflow runs on your machine

    steps:
      - name: Set up Docker Compose
        run: |
          docker-compose --version

      - name: Change to app directory
        run: |
          cd /home/ashik/selise/Projects/demoapp/
          pwd # Print working directory for debugging
          ls -la # List files for debugging
      - name: Checking out code
        run: |
          git stash
          git fetch
          git pull origin main

      - name: Deploy with Docker Compose
        run: |
          # Build and start the containers
          docker-compose up -d --build

          # Remove unused images
          docker image prune -f
